=== Hobbyhobbit/musik/schrumm.dtd
<!ELEMENT songsheet ( info, song )>

<!ELEMENT info (( title | composer | year | genre | key | capo | beat | tags)* , note?) >

	<!ELEMENT title ( #PCDATA )>
	<!ELEMENT composer ( #PCDATA )>
	
	<!ELEMENT year ( #PCDATA )>
	<!ELEMENT genre ( #PCDATA )>
	<!ELEMENT key ( chord )>
	<!ATTLIST key original CDATA #IMPLIED>
	<!ELEMENT capo ( #PCDATA )>
	<!ELEMENT beat ( #PCDATA )>
	
	<!ELEMENT tags ( (tag)* )>
		
		<!ELEMENT tag ( #PCDATA )>


<!ELEMENT song ( stanza | note )* >

	<!ELEMENT stanza ( #PCDATA | br | chord | bar )* >
	<!ATTLIST stanza
		type ( chorus | verse | bridge ) #IMPLIED
		id ID #IMPLIED
	>
	
		<!ELEMENT br EMPTY>
		<!ELEMENT chord EMPTY>
		<!ELEMENT bar EMPTY>
		<!ATTLIST chord 
			name CDATA #REQUIRED
		>
		
<!ELEMENT note ( #PCDATA )>

=== Hobbyhobbit/musik/sammlung/people cmon.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE songsheet SYSTEM "http://people.ee.ethz.ch/~maroggo/musik/schrumm.dtd">
<?xml-stylesheet type="text/css" href="http://people.ee.ethz.ch/~maroggo/musik/schrumm.css" ?>

<songsheet>
<info>
	<title>People Câ€™mon</title>
	<composer>Delta Spirit</composer>
	
	<key original="9"> <chord name="Cm" /> </key>
	<year>2009</year>
	<genre>Surf-Folk</genre>
	<beat>8/8</beat>
	
</info>

<song>
	<stanza type="verse">
		I'm a wandering <chord name="em" />soul<br />
		I got no place of my <chord name="H" />own<br />
		Well I got nothing to <chord name="em" />give<br />
		Well I got nothing to <chord name="H" />show for it
	</stanza>
	
	<stanza type="bridge">
		And I'll be wondering <chord name="D" />all, for all my <chord name="em" />years<br />
		What I be<chord name="H" />come no one could <chord name="am" />know
	</stanza>
	<stanza type="chorus">
		If you're <chord name="em" />feeling what I'm feeling <chord name="H" />c'mon<br />
		All you soul searching people <chord name="em" />c'mon
	</stanza>
	
	<stanza type="verse">
		And I got something to say my friends<br />
		I will never lay down without a fight<br />
		And when I die it will be the day<br />
		When every one of my wrongs will be made right
	</stanza>
	
	<stanza type="verse">
		Only times gonna heal my pain<br />
		Lord knows the mistakes I will make<br />
		Yeah there'll be peace on my soul someday<br />
		Reconside I'll be on my way
	</stanza>
	
	<stanza type="bridge">
		And I'll be wondering all, for all my years<br />
		What I become no one could know
	</stanza>
	<stanza type="chorus">
		If you're feeling what I'm feeling c'mon<br />
		All you soul searching people c'mon<br />
		Oh no, if you're feeling what I'm feeling c'mon<br />
		All you soul searching people c'mon
	</stanza>
	
	<note>Ba, badapap daa....</note>
	
	<stanza type="bridge">
		And I'll be wondering all, for all these years<br />
		What I become no one could know
	</stanza>
	<stanza type="chorus">
		If you're feeling what I'm feeling c'mon<br />
		All you soul searching people c'mon
	</stanza>
</song>
</songsheet>

=== Hobbyhobbit/musik/altes/neu.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE songsheet SYSTEM "http://people.ee.ethz.ch/~maroggo/musik/schrumm.dtd">
<?xml-stylesheet type="text/css" href="http://people.ee.ethz.ch/~maroggo/musik/schrumm.css" ?>

<songsheet>
<info>
	<title>L'ours</title>
	<composer>Tricot Machine</composer>
	
	<key original="2"> <chord name="cm" /> </key>
	<capo>3</capo>
	<year>2010</year>
	<genre>was auch immer</genre>
	<beat>8/8</beat>
	
</info>

<song>
	<stanza type="verse">
		J’ai <chord name="cm" />sauvé la <chord name="Bb" />peau d’un p’tit <chord name="Es" />ours<br />
		Pis son <chord name="cm" />coeur, je <chord name="Bb" />l’ai pas <chord name="Es" />volé<br />
		J’ai <chord name="cm" />tué le chas<chord name="Gm" />seur avant qu’il <chord name="As" />shoote<br />
		Et l’ours m’a consol<chord name="cm" />ée
	</stanza>
	
	<stanza type="verse">
		Tu es doux et juste un peu farouche<br />
		Mais je sais que je t’aprivoiserai<br />
		Tu as mordu dans mon coeur à pleine bouche<br />
		Et t’y est installé
	</stanza>
	
	<stanza type="verse">
		Les années se suivent et nous rassemblent<br />
		Il y a toujours plus à partager<br />
		Dans la tanière qui abrite nos confidences<br />
		Nous on a hiberné
	</stanza>
	
	<stanza type="verse">
		Puis un jour c’est l’été et c’est dimanche<br />
		Et les framboises poussent par milliers<br />
		J’ai tâché de fruits rouges ma robe blanche<br />
		Et je vais t’épouser
	</stanza>
	
	<stanza type="verse">
		Les yeux fermés, main dans la patte, on avance<br />
		Dans l’allée d’un champs d’blé d’inde shooté<br />
		Un doux mélange de romance et de démence<br />
		Quand le fermier a tiré
	</stanza>
	
	<stanza type="verse">
		Ce matin je me suis faite une p’tite bouffe<br />
		Mais à vrai dire ça passait pas vraiment<br />
		J’m’étais même préparé un bol de soupe<br />
		Et j’espérais te voir dedans
	</stanza>
	
	<stanza type="verse">
		Mais en vain, je l’ai scruté à galops<br />
		Aucune trace de toi dedans, de sang<br />
		Dis t’es où à présent, mon p’tit ours<br />
		Ta fourrure traîne sur le divan
	</stanza>
</song>
</songsheet>

=== Hobbyhobbit/musik/sammlung/lord anthony.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE songsheet SYSTEM "http://people.ee.ethz.ch/~maroggo/musik/schrumm.dtd">
<?xml-stylesheet href="http://people.ee.ethz.ch/~maroggo/musik/schrumm.css"?><songsheet>

<info>
	<title>Lord Anthony</title>
	<composer>Belle &amp; Sebastian</composer>
	
	<key original="0"><chord name="cm"/></key>
	<year>Jahr: 1998</year>
	<beat>Takt: 8/8</beat>
	
	<tags><tag>Bilingue</tag> <tag>Schnulzig</tag> <tag/></tags>
	
</info>

<song>
	<stanza type="verse"><chord name="cm"/>
		Wie seltsam <chord name="fm6"/>verlassen <br/><chord name="cm"/>und verweht du <chord name="Bb"/>aus<chord name="G"/>siehst <br/><chord name="cm"/>Wie deine Farben <chord name="fm6"/>verblassen <br/><chord name="cm"/>wenn man vom Trubel <chord name="Bb"/><chord name="G"/>abbiegt <br/> <br/><chord name="fm"/>Ach, wie dein Herz zu <chord name="cm"/>schlagen anfängt <br/><chord name="Es"/>wie der Stein sanft <chord name="D"/>erbebt <chord name="G"/>zugleich <br/><chord name="fm"/>Ach, wie die Geschichte in die <chord name="cm"/>Gassen sich hängt <br/><chord name="Es"/>Erst <chord name="D"/>jetzt bist du <chord name="G"/>reich
	 </stanza>
	<stanza type="verse">
		Wie seltsam deine Häuser träumen <br/>als schwebten sie in and‘rer Zeit <br/>Wären aus Wolken all die Bäume <br/>du flögst wohl in die Vergangenheit <br/> <br/>Ach, hättest du nicht harte Glieder <br/>ich läge dir im weichen Schoss <br/>Ich würd‘ dir singen all die Lieder <br/>Wär‘ dein Ohr nur riesengross
	 </stanza>
	<stanza type="chorus"><chord name="cm"/>
		Fribourg, mon <chord name="fm"/>amour <br/><chord name="Es"/>Fribourg, je t‘aime pour <chord name="G"/>toujours <br/><chord name="cm"/>Fribourg, mon <chord name="fm"/>amour <br/><chord name="Es"/>Fribourg, je t‘aime pour <chord name="G"/>toujours <br/> </stanza>
	<stanza type="verse">
		Wie seltsam deine Wasser fliessen <br/>Als wärst du eines Seemanns Hort <br/>Würd‘ sich ein Meer auf dich ergiessen <br/>Du taugtest noch als sicheren Port <br/> <br/>Ach, wär‘ dein Dom nicht längst am klingen <br/>baute ich einen dir aus reinstem Gold <br/>Trüge dein Geist nicht längst schon Schwingen <br/>hätte ich vom Himmel dir welche geholt <br/> </stanza>
	
	<note>Refrain</note>
	
</song>

</songsheet>

=== Hobbyhobbit/musik/sammlung/mad world.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE songsheet SYSTEM "http://people.ee.ethz.ch/~maroggo/musik/schrumm.dtd">
<?xml-stylesheet type="text/css" href="http://people.ee.ethz.ch/~maroggo/musik/schrumm.css" ?>

<songsheet>
<info>
	<title>Mad World</title>
	<composer>Michael Andrews</composer>
	
	<key original="-1"> <chord name="Em" /> </key>
	<year>2001</year>
	<genre>Pop</genre>
	<beat>4/4</beat>
	
</info>

<song>
	<stanza type="verse">
		I'm a wandering <chord name="em" />soul<br />
		I got no place of my <chord name="H" />own<br />
		Well I got nothing to <chord name="em" />give<br />
		Well I got nothing to <chord name="H" />show for it
	</stanza>
	
	<stanza type="bridge">
		And I'll be wondering <chord name="D" />all, for all my <chord name="em" />years<br />
		What I be<chord name="H" />come no one could <chord name="am" />know
	</stanza>
	<stanza type="chorus">
		If you're <chord name="em" />feeling what I'm feeling <chord name="H" />c'mon<br />
		All you soul searching people <chord name="em" />c'mon
	</stanza>
</song>
</songsheet>

=== Hobbyhobbit/musik/sammlung/fribourg, mon amour.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE songsheet SYSTEM "http://people.ee.ethz.ch/~maroggo/musik/schrumm.dtd">
<?xml-stylesheet type="text/css" href="http://people.ee.ethz.ch/~maroggo/musik/schrumm.css" ?>

<songsheet>
<info>
	<title>Fribourg, mon amour</title>
	<composer>Gustav</composer>
	
	<key original="0"> <chord name="cm" /> </key>
	<year>1998</year>
	<beat>8/8</beat>
	
	<tags>
		<tag>Bilingue</tag>
		<tag>Schnulzig</tag>
	</tags>
	
</info>

<song>
	<stanza type="verse">
		<chord name="cm" />Wie seltsam ver<chord name="fm6" />lassen<br />
		<chord name="cm" />und verweht du <chord name="Bb" />aussiehst<chord name="G" /><br />
		<chord name="cm" />Wie deine Farben verb<chord name="fm6" />lassen<br />
		<chord name="cm" />wenn man vom Trubel ab<chord name="Bb" />biegt<chord name="G" /><br />
		<br />
		<chord name="fm" />Ach, wie dein Herz zu sch<chord name="cm" />lagen anfängt<br />
		<chord name="Es" />wie der Stein sanft er<chord name="D" />bebt zugl<chord name="G" />eich<br />
		<chord name="fm" />Ach, wie die Geschichte in die <chord name="cm" />Gassen sich hängt<br />
		<chord name="Es" />Erst <chord name="D" />jetzt bist du r<chord name="G" />eich
	</stanza>
	<stanza type="verse">
		Wie seltsam deine Häuser träumen<br />
		als schwebten sie in and‘rer Zeit<br />
		Wären aus Wolken all die Bäume<br />
		du flögst wohl in die Vergangenheit<br />
		<br />
		Ach, hättest du nicht harte Glieder<br />
		ich läge dir im weichen Schoss<br />
		Ich würd‘ dir singen all die Lieder<br />
		Wär‘ dein Ohr nur riesengross
	</stanza>
	<stanza type="chorus">
		<chord name="cm" />Fribourg, mon a<chord name="fm" />mour<br />
		<chord name="Es" />Fribourg, je t‘aime pour tou<chord name="G" />jours<br />
		<chord name="cm" />Fribourg, mon a<chord name="fm" />mour<br />
		<chord name="Es" />Fribourg, je t‘aime pour tou<chord name="G" />jours<br />
	</stanza>
	<stanza type="verse">
		Wie seltsam deine Wasser fliessen<br />
		Als wärst du eines Seemanns Hort<br />
		Würd‘ sich ein Meer auf dich ergiessen<br />
		Du taugtest noch als sicheren Port<br />
		<br />
		Ach, wär‘ dein Dom nicht längst am klingen<br />
		baute ich einen dir aus reinstem Gold<br />
		Trüge dein Geist nicht längst schon Schwingen<br />
		hätte ich vom Himmel dir welche geholt<br />
	</stanza>
	
	<note>Refrain</note>
	
</song>
</songsheet>

=== Hobbyhobbit/musik/sammlung/readme.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE songsheet SYSTEM "http://people.ee.ethz.ch/~maroggo/musik/schrumm.dtd">
<?xml-stylesheet type="text/css" href="http://people.ee.ethz.ch/~maroggo/musik/schrumm.css" ?>

<songsheet>
<info>
	<title>Schrumm-Markup</title>
	<composer>Matthias</composer>
	
	<year>2011</year>
	<genre>Yet Antother Chord Markup Language</genre>
	
	<note>Kommentare im Infobereich müssen immer am Schluss stehen</note>
	
</info>

<song>
	<stanza type="verse">
		Die <chord name="H" />Strophen werden nummeriert<br />
		I got no place of my <chord name="H" />own<br />
		Well I got nothing to <chord name="em" />give<br />
		Well I got nothing to <chord name="H" />show for it
	</stanza>
	
	<stanza type="bridge">
		And I'll be wondering <chord name="D" />all, for all my <chord name="em" />years<br />
		What I be<chord name="H" />come no one could <chord name="am" />know
	</stanza>
	<stanza type="chorus">
		If you're <chord name="em" />feeling what I'm feeling <chord name="H" />c'mon<br />
		All you soul searching people <chord name="em" />c'mon
	</stanza>
	
	<note>Und jetzt: ALLE!</note>
	
	<stanza type="verse">
		...wobei Bridge und Refrain nicht gezählt werden<br />
		I got no place of my <chord name="H" />own<br />
		Well I got nothing to <chord name="em" />give<br />
		Well I got nothing to <chord name="H" />show for it
	</stanza>
	
	<note>Klappt noch nicht: Akkordfolge ohne Text</note>

</song>
</songsheet>
